TYPE_ICONS = {
    "Normal": "https://archives.bulbagarden.net/media/upload/8/89/Normal_icon_SwSh.png",
    "Fuego": "https://archives.bulbagarden.net/media/upload/a/ab/Fire_icon_SwSh.png",
    "Agua": "https://archives.bulbagarden.net/media/upload/8/80/Water_icon_SwSh.png",
    "Planta": "https://archives.bulbagarden.net/media/upload/a/a8/Grass_icon_SwSh.png",
    "Eléctrico": "https://archives.bulbagarden.net/media/upload/7/7b/Electric_icon_SwSh.png",
    "Hielo": "https://archives.bulbagarden.net/media/upload/1/15/Ice_icon_SwSh.png",
    "Lucha": "https://archives.bulbagarden.net/media/upload/3/3b/Fighting_icon_SwSh.png",
    "Veneno": "https://archives.bulbagarden.net/media/upload/8/8d/Poison_icon_SwSh.png",
    "Tierra": "https://archives.bulbagarden.net/media/upload/2/27/Ground_icon_SwSh.png",
    "Volador": "https://archives.bulbagarden.net/media/upload/b/b5/Flying_icon_SwSh.png",
    "Psíquico": "https://archives.bulbagarden.net/media/upload/7/73/Psychic_icon_SwSh.png",
    "Bicho": "https://archives.bulbagarden.net/media/upload/9/9c/Bug_icon_SwSh.png",
    "Roca": "https://archives.bulbagarden.net/media/upload/1/11/Rock_icon_SwSh.png",
    "Fantasma": "https://archives.bulbagarden.net/media/upload/0/01/Ghost_icon_SwSh.png",
    "Dragón": "https://archives.bulbagarden.net/media/upload/7/70/Dragon_icon_SwSh.png",
    "Siniestro": "https://archives.bulbagarden.net/media/upload/d/d5/Dark_icon_SwSh.png",
    "Acero": "https://archives.bulbagarden.net/media/upload/0/09/Steel_icon_SwSh.png",
    "Hada": "https://archives.bulbagarden.net/media/upload/c/c6/Fairy_icon_SwSh.png",
}